# Generated by Django 3.0.6 on 2020-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200714_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='z',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
